export const stackIcons = [
  { title: "React", href: "https://react.dev", src: "/icons/thesvg/react.svg" },
  { title: "Next.js", href: "https://nextjs.org", src: "/icons/thesvg/nextdotjs.svg" },
  { title: "Tailwind CSS", href: "https://tailwindcss.com", src: "/icons/thesvg/tailwind-css.svg" },
  { title: "TypeScript", href: "https://typescriptlang.org", src: "/icons/thesvg/typescript.svg" },
  { title: "JavaScript", href: "https://developer.mozilla.org/docs/Web/JavaScript", src: "/icons/thesvg/javascript.svg" },
  { title: "Node.js", href: "https://nodejs.org", src: "/icons/thesvg/nodedotjs.svg" },
  { title: "Bun", href: "https://bun.sh", src: "/icons/thesvg/bun.svg" },
  { title: "Vite", href: "https://vite.dev", src: "/icons/thesvg/vite.svg" },
  { title: "Vue", href: "https://vuejs.org", src: "/icons/thesvg/vue.svg" },
  { title: "Svelte", href: "https://svelte.dev", src: "/icons/thesvg/svelte.svg" },
  { title: "GitHub", href: "https://github.com", src: "/icons/thesvg/github.svg" },
  { title: "Docker", href: "https://docker.com", src: "/icons/thesvg/docker.svg" },
  { title: "PostgreSQL", href: "https://postgresql.org", src: "/icons/thesvg/postgresql.svg" },
  { title: "MongoDB", href: "https://mongodb.com", src: "/icons/thesvg/mongodb.svg" },
  { title: "MySQL", href: "https://mysql.com", src: "/icons/thesvg/mysql.svg" },
  { title: "Redis", href: "https://redis.io", src: "/icons/thesvg/redis.svg" },
  { title: "Cloudflare", href: "https://cloudflare.com", src: "/icons/thesvg/cloudflare.svg" },
  { title: "Railway", href: "https://railway.com", src: "/icons/thesvg/railway.svg" },
  { title: "Supabase", href: "https://supabase.com", src: "/icons/thesvg/supabase.svg" },
  { title: "Vercel", href: "https://vercel.com", src: "/icons/thesvg/vercel.svg" },
];
